### ISSUE TITLE
create ONNX for anylabeling

### ISSUE THREAD

**Issue by aiyou9** [facebookresearch/ov-seg#11]
I want import OV-seg to anylabeling, please give ONNX format or some advise for me, thanks a lot !
https://github.com/vietanhdev/anylabeling

**Comment by Jeff-LiangF** [comment]
Hi @aiyou9 ,

Thanks for your interest! Unfortunately, we don't have an ONNX format and don't have a plan either. You are very welcome to do it by yourself and we would definitely help you to do so.

I noticed in [anylabeling](https://github.com/vietanhdev/anylabeling) you have an implementation of SAM. We incorporate OVSeg CLIP w/ SAM, enabling SAM’s text prompts, try our demo in [hf ovseg](https://huggingface.co/spaces/facebook/ov-seg). Regarding the implementation, I believe it should be easy since you only need to convert the [OVSeg CLIP](https://huggingface.co/spaces/facebook/ov-seg/blob/main/ovseg_clip_l_9a1909.pth) to the ONNX format. Our OVSeg CLIP has the exact format as OpenAI's CLIP, so you may easily find the tutorials to convert CLIP to ONNX. 

Feel free to reopen this issue or directly reach out to me if you have any questions. Thanks!
