### ISSUE TITLE
CLIP weights?

### ISSUE THREAD

**Issue by ghost** [facebookresearch/ov-seg#6]
Hi @all,
Thank you for your great work.
Your work has two implication 1) the segmentation model with Mask prompting, 2) the Embedding of your new CLIP model (that have a mask image and a mask prompt as inputs).

For now, I just found that you provided the weights for the entire model (segmentation model), so could you provide us with the new CLIP weights? I think it is really helpful because your work help CLIP learns the region-level image (as in RegionCLIP). 

And do you plan to work on ViT-B/32? because I just found the ViT-B/16 and ViT-L/16 versions.
Thank you very much.

Best,
Tin

**Comment by Jeff-LiangF** [comment]
Hi @ngthanhtin,

Please check out finetuned CLIP model: [ViT-B/16](https://drive.google.com/file/d/1s4QhyYLnRctMrBkMw7BV6nXsxgdhpkcc/view?usp=drive_link) and [ViT-L/14](https://drive.google.com/file/d/17C9ACGcN7Rk4UT4pYD_7hn3ytTa3pFb5/view?usp=drive_link). These models follow the extract same format as OpenAI's CLIP so that you can conduct an apple-to-apple comparison. You can easily use [open_clip v1.3](https://github.com/mlfoundations/open_clip/tree/v1.3.0) to load the model weights.

```
self.clip_model, _, _ = open_clip.create_model_and_transforms('ViT-L-14', pretrained=ovsegclip_path)
```

Unfortunately, we don't have ViT-B/32 weights. You may want to use our [open clip training](https://github.com/facebookresearch/ov-seg/tree/main/open_clip_training) to train your own CLIP ViT-B/32 with our mask-text pairs data.
